# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
    - name: Bump Version
      if: github.ref == 'refs/heads/master'
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          bump2version patch
          git push --tags
    - name: Build dist
      if: github.ref == 'refs/heads/master'
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      if: github.ref == 'refs/heads/master'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
